language: cpp
sudo: true
compiler:
  - g++
before_install:
  - sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
install: sudo apt-get update -qq
script:
  - cmake CMakeLists.txt && make

