language: cpp
sudo: true
compiler:
  - g++
before_install:
  - yes | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
install: sudo apt-get update -qq
before_script:
  - BUILD_DIR=`pwd`/builds
  - mkdir -p ${BUILD_DIR}
script:
  - cmake ../CMakeLists.txt && make

